### ISSUE TITLE
Text is not being copied to the extension space

### ISSUE THREAD

**Issue by Bart-van-Ingen** [robindijkhof/overleaf-textarea#13]
I have installed Grammarly and the extension, only the extension does not automatically copy the text from the tex file as shown in the image below:

![image](https://user-images.githubusercontent.com/36703540/97710436-0b424b80-1abc-11eb-9e8f-79097f66f73f.png)

What could be causing this? Could it be the fact that I am using chrome on ubuntu?

**Comment by robindijkhof** [comment]
Could you post the tex file?

**Comment by tejaslodaya** [comment]
+1

Same is happening for me. It just comes out as blank.

**Comment by robindijkhof** [comment]
@tejaslodaya can you post your tex file here? And maybe check the console?

**Comment by Bart-van-Ingen** [comment]
In my case the example that i showed above is filler tex. Either way it should still work in the extension.
Here is the Tex

``` tex
% Dedication page. 
\cleardoublepage
\thispagestyle{empty}
\vspace*{\stretch{1}}

% Put your own motto here, or dedicate your work to your Mom or whatever...
\begin{quote}
\noindent``In the future, airplanes will be flown by a dog and a pilot. And the dog's job will be to make sure that if the pilot tries to touch any of the buttons, the dog bites him.''
	
--- \emph{Scott Adams}
\end{quote}

\vspace{\stretch{3}}
\clearemptydoublepage
```

**Comment by Bart-van-Ingen** [comment]
this is what my console is showing
![image](https://user-images.githubusercontent.com/36703540/97776852-076e0200-1b6c-11eb-8403-aa7ff33414ec.png)

**Comment by robindijkhof** [comment]
It appears `replaceAll` is not widely supported. Can you check your Chrome version?
![image](https://user-images.githubusercontent.com/22224763/97781795-0b128080-1b8e-11eb-8587-6e7e9b0d578f.png)

**Comment by Bart-van-Ingen** [comment]
This is my google chrome version:
![image](https://user-images.githubusercontent.com/36703540/97784149-b62a3680-1b9c-11eb-84b0-5e84e2aa2041.png)

**Comment by tejaslodaya** [comment]
Ah, mine is 76.0.3809.132 (Official Build) (64-bit).

It makes sense now.
@robindijkhof can you add this requirement in the project README.md?

**Comment by robindijkhof** [comment]
I'll first try some workaround.

**Comment by andreamoro-git** [comment]
Firefox here. THis is a sample tex code where it doesn't work.

`\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{amsmath,amsfonts,bbm}
\usepackage[margin=1.5in]{geometry}
\usepackage{amsthm}
\titleadf}
\author{me}
\date{October 2020}

\begin{document}

\maketitle

Consider 
This is two applers.
This is three countars

\end{document}
`

**Comment by robindijkhof** [comment]
@Bart-van-Ingen and @tejaslodaya I think I have some workaround. If you are still on older versions of Chrome, can you check if it works now?

**Comment by andreamoro-git** [comment]
It works on chrome, not on firefox. Thanks

**Comment by tejaslodaya** [comment]
@robindijkhof can you push the update/give me the script branch where I can test?

**Comment by robindijkhof** [comment]
It is in master and should also be published already

**Comment by Bart-van-Ingen** [comment]
I already update to a newer version of chrome. Sorry!

**Comment by tejaslodaya** [comment]
I switched to firefox, sorrry!
