### ISSUE TITLE
Firefox Plugin does not merges changes back the editor 

### ISSUE THREAD

**Issue by andreamoro-git** [robindijkhof/overleaf-textarea#14]
Firefox user. I am not sure how merging is supposed to occur, but the plugin does not seem to do it in Firefox. BTW the firefox plugin install page is only in Dutch.

**Comment by andreamoro-git** [comment]
duplicates existing issue

**Comment by robindijkhof** [comment]
I don't think this is a duplicate issue. I am seeing the same problem on FF. For some reason, changes made by Grammarly are not detected. Weird thing is that changes made by FF spellcheck ARE detected. I'll see what I can do.

**Comment by andreamoro-git** [comment]
From what I see, they are detected, but once grammarly makes the change, the plugin merges the original text back to the textarea. You can see it because the change stays in the textarea for a fraction of a second before reverting to the original

**Comment by andreamoro-git** [comment]
https://streamable.com/crehem

**Comment by robindijkhof** [comment]
I just released an update to fix this. Can you check it?

**Comment by andreamoro-git** [comment]
Seems to be working now.
