### ISSUE TITLE
Use the "hi there!" box to toggle PDF/Textarea

### ISSUE THREAD

**Issue by andreamoro-git** [robindijkhof/overleaf-textarea#15]
Perhaps a button somewhere?

**Comment by andreamoro-git** [comment]
I would actually use a different approach to usability, I have no idea how feasible it is: keep the pdf on the right, but open the textarea at the bottom of the overleaf editor. Then include an expand/collapse button somewhere, could be the url bar

**Comment by robindijkhof** [comment]
https://github.com/robindijkhof/overleaf-textarea/issues/21
