### ISSUE TITLE
Extra blank lines are omitted 

### ISSUE THREAD

**Issue by IantheChan** [robindijkhof/overleaf-textarea#17]
I want to use this for the revision of a thesis. However, I noticed that the red line that highlighting the error did not match the test. There are extra blank lines in my original tex files and it seems that these lines are omitted in textarea.

**Comment by robindijkhof** [comment]
Can you provide an example?


Op ma 16 nov. 2020 04:35 schreef Ianthe <notifications@github.com>:

**Comment by IantheChan** [comment]
This the link for a simple example.
https://www.overleaf.com/read/jnstrfctqfkc
And also the screenshot is provided.
![1](https://user-images.githubusercontent.com/34849576/99221660-f1269e00-281b-11eb-8bac-58bf89f8abf4.jpg)

**Comment by robindijkhof** [comment]
That is some grammarly issue that happens sometimes. It happens when the text is changed or scrolled while grammarly is busy. There is not much I can do about that.

**Comment by IantheChan** [comment]
Thanks!
