### ISSUE TITLE
[Feature] add compatibility for self hosted variant

### ISSUE THREAD

**Issue by jonasbareiss** [robindijkhof/overleaf-textarea#18]
Overleaf / Sharelatex offers the possibility to self host, as for example many Universities do.
It would be awesome to be able to change on which URLs the plugin looks for an Overleaf instance.

**Comment by TobyUllrich** [comment]
I have the same problem right now working on my master thesis on my university sharelatex server. I would be really cool if self-hosted sites work as well

**Comment by robindijkhof** [comment]
Not sure if this is possible. I don't want to enable the plugin on all website. Needs some investigation. https://stackoverflow.com/questions/34957319/how-to-listen-for-url-change-with-chrome-extension and https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/pageAction

**Comment by Venturina** [comment]
I had the same issue.
However, as a basic workaround, I just changed the URL to my private server's URL in the code.

It's not the nicest thing to work with, however, it got me where I wanted.. Having Grammarly on my private hosted overleaf.

**Comment by robindijkhof** [comment]
https://stackoverflow.com/questions/41122368/dynamically-modify-content-scripts-matches-in-firefox-extension

**Comment by robindijkhof** [comment]
This should now be possible. Check the readme instructions and wait for the update.
