### ISSUE TITLE
Unable to use plugin

### ISSUE THREAD

**Issue by jbunzel92** [robindijkhof/overleaf-textarea#20]
Hey Robin,

seems like the plugin that I was looking for and it seems to run for everyone else but me. 
It doesn't work with Firefox/Chrome. I tried to restart Chrome/Firefox or my computer. I deactivated other plugins, I'm logged into Grammarly (using the plugin of course). 
As mentioned in the comment section of the Youtube video linked on the Chrome extension page, there should be a popup that allows enabling the textarea, but I don't get a popup at all. 
Any ideas?

Chrome: 87.0.4280.88 
Firefox: 83.0 

Best,

Julian

**Comment by robindijkhof** [comment]
In FF there should be an icon visible in the URL bar. In Chrome it is probably under the "puzzle piece"?? icon.

**Comment by jbunzel92** [comment]
I forgot that they moved it into the URL bar in FF, I can access it there. Thanks a lot. 👍  
For Chrome I can't get it running though. I can find the button but when I click it, I don't get the extension-specific popup but a generic chrome popup that simply shows some options like "Remove from Chrome", "Pin"/"Unpin" etc. If I try to access it via the puzzle piece icon it's greyed out compared to the other addons. 
Thanks for your help anyway!

Best,
Julian
