### ISSUE TITLE
Donations broken

### ISSUE THREAD

**Issue by aolney** [robindijkhof/overleaf-textarea#25]
I've tried donating on two different days, and each time, PayPal says "Something went wrong, try again later".

This happens on the final PayPal screen.

**Comment by robindijkhof** [comment]
That is weird. I made a small change to the URL in the readme. Could you try that one? [Or this one](https://www.paypal.com/donate/?hosted_button_id=6B3GESXVWUPAJ)

**Comment by aolney** [comment]
It's very strange - I'm continuing to get this error:

![donation-break](https://user-images.githubusercontent.com/4432084/102945164-97e90480-4482-11eb-9461-8ec7a0dced29.png)

It looks like this is [something that happens when people try to pay with a card](https://www.paypal-community.com/t5/PayPal-Payments-Standard/Button-gives-quot-Something-went-wrong-quot-error-after/td-p/1592600) sometimes.

**Comment by aolney** [comment]
Maybe this is the answer: https://www.paypal-community.com/t5/Merchant-Products-and-Services/Donation-by-Credit-card-works-on-Safari-and-Mozilla-but-not-on/td-p/1541185

**Comment by robindijkhof** [comment]
I couldn't find much about this. Are you using the link in my comment or some other method?

**Comment by aolney** [comment]
I've tried both paying with a credit card and logging into PayPal, both with the original URL and the new one. However, both times I used Chrome. I'll try again with Firefox now.

**Comment by aolney** [comment]
Getting the same error from Firefox using https://www.paypal.com/donate/?hosted_button_id=6B3GESXVWUPAJ 

Tried also with Chrome and got same error.

**Comment by aolney** [comment]
Also just tried from Chrome on Android with no success. 

In each case, it gets to the final confirm screen (which has conversion information from dollars to euros) and then throws the error above.

**Comment by Venturina** [comment]
I tried from Chrome on Windows, worked well!

**Comment by robindijkhof** [comment]
I think there is not much I can do about this.

**Comment by aolney** [comment]
Just tried again from a Chromebook and succeeded 👍
