### ISSUE TITLE
The text area isn't appearing

### ISSUE THREAD

**Issue by jacksonraniel** [robindijkhof/overleaf-textarea#26]
Hi,

I've just installed the Chrome extension and Firefox AddOn, but in both cases, the text area is just not appearing when I'm editing with the Overleaf.

I'm using Firefox version 84.0.2 and Chrome version 87.0.4280.141. Can you help me with it?

**Comment by robindijkhof** [comment]
Did you Activate the plugin by clicking the plugin and enabling the checkbox. As described in the instructions

**Comment by jacksonraniel** [comment]
Yes, I did.

The plugin is activated in both browsers. 

![Captura de tela de 2021-01-13 14-32-45](https://user-images.githubusercontent.com/692083/104487987-88099f80-55ac-11eb-85b3-128c1450a4e1.png)
![Captura de tela de 2021-01-13 14-33-03](https://user-images.githubusercontent.com/692083/104488002-8cce5380-55ac-11eb-867d-02fe34c784ad.png)

**Comment by robindijkhof** [comment]
Should do like this.

![image](https://user-images.githubusercontent.com/22224763/104495023-85706f80-55d7-11eb-90c1-dd45262dce3d.png)
