### ISSUE TITLE
[Bug] Cannot disable textarea

### ISSUE THREAD

**Issue by teryakizhang** [robindijkhof/overleaf-textarea#27]
I understand this is a chrome native plugin, however, I think it may still be worth raising this issue in case it's not isolated to Opera. Since yesterday textarea would be enabled by default when I opened a project on Overleaf and I could not disable it using the active checkbox. Only fixed it by disabling the whole plug-in.

**Comment by robindijkhof** [comment]
The same thing happens to me on chrome. Guess there is something wrong with the active checkbox. The first time does not work, third time does though.

**Comment by rgudwin** [comment]
When I click on the option "Enable Overleaf textarea on this domain", the following popup opens on overleaf:
![image](https://user-images.githubusercontent.com/7912248/105050479-92b0b280-5a4c-11eb-8e4d-5a723d87da3a.png)
And nothing else happens ... if I click Ok the popup dismisses, but nothing more.

**Comment by robindijkhof** [comment]
@rgudwin the  "Enable Overleaf textarea on this domain" is only for domains other than overleaf.com. For instance muselfhostedoverleaf.com. Therefore you can't disable it. Please check the instructions on how to (de)active the plugin.

**Comment by rgudwin** [comment]
@robindijkhof many thanks ! I was misunderstanding how to enable/disable the textarea. Now I understood. But I second others opinions expressed in other topics, that it would be interesting to have a one-click way for doing that. As it is, I have first to click in the pin for the menu to show and then click in "Active" to turn the textarea on/off, so it's two clicks. It would be nice to be able to do that with just one click somewhere, or using a CTRL-<something> key. Nevertheless ... nice work ! A very useful plugin ! Just a last question ... what is the purpose of the bottom part of the textarea with the message "Hi, there" ?

**Comment by robindijkhof** [comment]
It shows errors for those who use incorrect custom filters. Might be removed later.

**Comment by krallistic** [comment]
Since two days i also have the same problem. Previously I could switch between modes, now textarea is permanently active. 

Chrome: Version 87.0.4280.141 (Official Build) (64-bit) on Linux.

**Comment by robindijkhof** [comment]
For me, pressing that active checkbox a few times fixes(3-5) the issue. Should still be fixed though.

**Comment by robindijkhof** [comment]
I can't really seem to reproduce this. Anyone else can?

**Comment by robindijkhof** [comment]
I can somewhat reproduce it be using the plugin in multiple tabs

**Comment by robindijkhof** [comment]
Fix in next release
