### ISSUE TITLE
Easy Enable/Disable of TextArea ? 

### ISSUE THREAD

**Issue by rgudwin** [robindijkhof/overleaf-textarea#28]
Hi, 
I am using the plugin with Google Chrome 87.0.4280.141 on Linux. I didn't found an easy way for enabling/disabling the textarea, and make the PDF view available again. I suppose the option "Enable Overleaf textarea on this domain" was for that purpose, but it is not working. Besides maybe fixing that, it will be interesting to have a CTRL-<something> key binding to switch the textarea on and off, so we could enable/disable the textarea view, depending on the situation.

**Comment by robindijkhof** [comment]
Guess there is something wrong with the active checkbox. The first time does not work, third time does though.

**Comment by robindijkhof** [comment]
https://github.com/robindijkhof/overleaf-textarea/issues/27
