### ISSUE TITLE
Label and autoref not being filtered

### ISSUE THREAD

**Issue by hakonw** [robindijkhof/overleaf-textarea#3]
Hi!

Firstly, thanks for creating the app!

While using it, I noticed that it does not filter out usages of `\label` and `\autoref`

```latex
\section{Multi sided platform}\label{sec:multi-sided-platform}

\autoref{sec:algorithm}
```

turns into 
```
Multi sided platform\label{sec:multi-sided-platform}

\autoref{sec:algorithm}
```

I do believe that `label` is regular latex, together often used with `\ref` ([wikibooks](https://en.wikibooks.org/wiki/LaTeX/Labels_and_Cross-referencing#Introduction)), so that should be added.

Also `autoref` is from the `hyperref` package, so what is your thought on adding filters for commands from packages?

Cheers!

**Comment by robindijkhof** [comment]
Hi, more filters should indeed be added. I have no idea what commands are supported by default, so I just added the ones I was using. It would be great if you could provide me with such a list.

I have no clear view on commands in other packages. I can imagine it would be nice to support the most used packages. Again, I have no idea which packages that should be.

There will always be people using 'fancy package X' so I am thinking of a way to create your own filters. This is more a future thing I guess.

**Comment by hakonw** [comment]
Hi!

> It would be great if you could provide me with such a list.  

I do not have a list, but one way would be to look at https://www.ntg.nl/doc/biemesderfer/ltxcrib.pdf, or hopefully something more machine-readable. 
In my opinion that is way too much work, and I agree with your choice of only including the most popular.


On where the filters are added, is [functions.js#L29](https://github.com/robindijkhof/overleaf-textarea/blob/master/functions.js#L29) currently the only way of adding new filters?
Will there be a more user-friendly way of adding them? Like parsing a config file?


Cheers!

**Comment by robindijkhof** [comment]
I added more filters and created a new issue for the custom user-defined filters.

**Comment by hakonw** [comment]
https://github.com/robindijkhof/overleaf-textarea/commit/7af508f2d16da13126f0401351de394531fd1888#diff-99adff4a611723728cb0d72f3e02b658cd9ac5ac2446a56c37afa149648a318aR78

Spelling mistake?

**Comment by robindijkhof** [comment]
Whoops, fixed that.

**Comment by robindijkhof** [comment]
@hakonw I added an option to create your own filters in the master branch. Could you play around with it a little?

**Comment by hakonw** [comment]
After using it a bit, it works, so that's nice.
With the default filter, it removes mostly everything I care for, so I only have 1 added custom filter.
Again, the issue is usability as you stated in #5. I don't have any huge ideas on how to improve that.
