### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by arashash** [robindijkhof/overleaf-textarea#31]
how could we use it in Google Colab markdown? there is enough similarity with Overleaf that it might just work!

**Comment by robindijkhof** [comment]
In its current state, you can't. Also, I think there are too many differences between Google Colab and Overleaf. Though the principle would be the same, the undelaying techniques aren't. Overleaf uses Ace Editor while Google Colab uses the Monaco Editor. Overleaf uses latex while Google Colab uses Markdown.

**Comment by arashash** [comment]
Thank you so much for the clarification. This app is awesome anyway, I would totally pay for it. Thanks

**Comment by robindijkhof** [comment]
Feel free to donate
