### ISSUE TITLE
Suggestion position not matching with the actual text.

### ISSUE THREAD

**Issue by DeerWhale** [robindijkhof/overleaf-textarea#32]
Hi, First I want to thank the author for writing such an awesome extension! But I do have an issue since the installation, the Grammarly suggestion does not match with the position of the corresponding text (see screenshot below).

I couldn't find any info about this, could this be a software/hardware issue on my side?  I will appreciate it if someone has a similar experience or know how to solve it. Thanks in advance! 
<img width="214" alt="Screen Shot 2021-02-03 at 12 18 09 PM" src="https://user-images.githubusercontent.com/48139543/106784086-f543aa00-6619-11eb-9e6c-6a913be3fc1d.png">

**Comment by robindijkhof** [comment]
This is something that just happens sometimes. A page refresh probably fixes it. Nothing I can do about it. Probably something with the Grammarly plugin since this plugin just presents a textarea with some text in it.
