### ISSUE TITLE
It looks that the tool is no more working !

### ISSUE THREAD

**Issue by AmineBarrak** [robindijkhof/overleaf-textarea#39]
When I start activate button, it just respond Hi there! without any corrections suggestion.

**Comment by robindijkhof** [comment]
It is working fine for me. Can you provide some more information? Did you check the readme?

**Comment by AmineBarrak** [comment]
This is a screenshot i took
https://user-images.githubusercontent.com/3717285/110322880-cab28b80-7fe1-11eb-9c91-46bfa62fac7a.png

**Comment by phHartl** [comment]
I got the same error, but I could fix it. In my case another browser plugin (Decentraleyes) interfered with overleaf-textarea. After disabling the aforementioned extension the plugin worked as described.

**Comment by robindijkhof** [comment]
@AmineBarrak did you try to disable other plugins?

**Comment by zachary-m** [comment]
I had to deactivate all my other plug-ins, enable pop-ups, are refresh the page to see the editor box on the right. However, the underlining and corrects do not seem to correspond to the text I am viewing. So, it does not really work.

**Comment by robindijkhof** [comment]
Incorrect underlining is a Grammarly issue. I'm updating the readme with some known problems.

**Comment by zachary-m** [comment]
To be honest, that seems like more of an issue with the extension than Grammarly. The extension does not provide text for which grammarly can work correctly.
