### ISSUE TITLE
Removing filters is buggy

### ISSUE THREAD

**Issue by jiriruzi** [robindijkhof/overleaf-textarea#40]
Sometimes, removing filter is buggy, meaning instead of the "clicked one" is deleted first one. 
How to reproduce:
Browser: Google Chrome
Add filters: a, b, c, d, e, f like in picture
![image](https://user-images.githubusercontent.com/26082563/114037527-5dfd0c00-9881-11eb-846a-70f76a7a262c.png)
Remove d or any other will result in removing a.

**Comment by robindijkhof** [comment]
Will be fixed in the next release
