### ISSUE TITLE
[Feature] Sync scroll

### ISSUE THREAD

**Issue by dsdoermann** [robindijkhof/overleaf-textarea#41]
This is great.  I will definitely be supporting this.  Is this the appropriate place to ask questions, or is there a forum?

Is there a way to 1) Sync the overleaf and your window?  2) Make more room for the Grammarly suggestions, so they don't overlap?

**Comment by dsdoermann** [comment]
The Grammarly window I solved by opening the chat panel and laying it over the top, so that is all set.

By sync, I mean is there any way when you scroll in the textarea panel (yours) that the overleaf panel to see the actual changes in the .tex document.



---------------------------
David Doermann
Professor, SUNY Empire Innovation
Professor, Department of Computer Science and Engineering
University at Buffalo

email: ***@***.***
website: cse.buffalo.edu/~doermann<http://cse.buffalo.edu/~doermann>
phone: 716-645-1557 (office), 410-493-9043 (mobile)

[footer_logo_03]
P Please consider the environment before printing this e-mail.

**Comment by robindijkhof** [comment]
This will be added in the next release

**Comment by dsdoermann** [comment]
Thank you!

---------------------------
David Doermann
Professor, SUNY Empire Innovation
Professor, Department of Computer Science and Engineering
University at Buffalo

email: ***@***.***
website: cse.buffalo.edu/~doermann<http://cse.buffalo.edu/~doermann>
phone: 716-645-1557 (office), 410-493-9043 (mobile)

[footer_logo_03]
