### ISSUE TITLE
FR: Remove single newlines

### ISSUE THREAD

**Issue by georgmartius** [robindijkhof/overleaf-textarea#46]
Grammarly expects a sentence in a single line. In tex, however, it does not matter whether one breaks the line anywhere.  
So my feature request would be to remove newlines if the next line is not empty.

**Comment by robindijkhof** [comment]
Hi, can you maybe give an example?

**Comment by georgmartius** [comment]
Lets say we write this in my latex:
"Here I am writing a nice sentence with grammar
mistake." 
with the newline after grammar.
Then (for me) Grammarly would not find the mistake that I either need plural or an article. If I remove the newline it does.

**Comment by robindijkhof** [comment]
Can you post a screenshot?

**Comment by georgmartius** [comment]
Here with the newline:
![image](https://user-images.githubusercontent.com/1215328/123330050-cdf46780-d53d-11eb-8326-be3478190a35.png)
Here without:
![image](https://user-images.githubusercontent.com/1215328/123330142-ef555380-d53d-11eb-928e-534da03c6029.png)

**Comment by robindijkhof** [comment]
Can't do that. The number of lines should be equal.

**Comment by georgmartius** [comment]
I see, thanks for your time anyway, and thanks for the helpful plugin!
