### ISSUE TITLE
Parsing Challenges

### ISSUE THREAD

**Issue by dsdoermann** [robindijkhof/overleaf-textarea#55]
When Captions (or anything?)  has embedded braces.  
LATEX

BEGIN CAPTION EMBEDDED WITH BRACES
->
\caption{START CAPTION The evolution of the prior $p(\bm{x})$, the distribution of the observation $\bm{y}$, and the posterior $p(\bm{x}|\bm{y})$ during learning, where $\bm{x}$ is the latent variable representing the full-precision parameters and $\bm{y}$ is the quantization error.  END CAPTION}
<-
END CAPTION EMBEDDED WITH BRACES

RESULT 

BEGIN CAPTION EMBEDDED WITH BRACES
->
)$, the distribution of the observation $\bm{y}$, and the posterior $p(\bm{x}|\bm{y})$ during learning, where $\bm{x}$ is the latent variable representing the full-precision parameters and $\bm{y}$ is the quantization error. END CAPTION}
<-
END CAPTION EMBEDDED WITH BRACES

**Comment by dsdoermann** [comment]
one solution seems to be to just dump to content:

{pattern: /(\\caption{)(.*?)(})/g, newValue: '$2'},

Do you see any problem with doing this with anything that may have embedded braces?

**Comment by robindijkhof** [comment]
I think there already might be a Mr for that. I'll check it out later

**Comment by robindijkhof** [comment]
I think this will be fixed in the next release
