### ISSUE TITLE
Citation latex error

### ISSUE THREAD

**Issue by GuillaumeP2705** [robindijkhof/overleaf-textarea#56]
Hi, 
I don't know how to solve it in your code, but an error occurred. When, in Overleaf for example, we have this type of code : 
`\cite{HELLOWORLD} done the job !` will produce " done the job !". But now, if the code is `This is a test as done in \cite{HELLOWORLD}, this is a great job!` will produce 'This is a test as done in". So all text after coma is deleted...

Thanks again for the plugin.

**Comment by robindijkhof** [comment]
Hi, I cannot reproduce this. Any chance you got a bigger example?

**Comment by Jpfonseca** [comment]
@robindijkhof  I just checked it in several docs and couldn't reproduce it too.

**Comment by dsdoermann** [comment]
This may have been the one you fixed earlier when you had two citations?  #50?

---------------------------
David Doermann
Professor, SUNY Empire Innovation
Professor, Department of Computer Science and Engineering
University at Buffalo

email: ***@***.***
website: cse.buffalo.edu/~doermann<http://cse.buffalo.edu/~doermann>
phone: 716-645-1557 (office), 410-493-9043 (mobile)

[footer_logo_03]
