### ISSUE TITLE
Shortcut to dis\en able?

### ISSUE THREAD

**Issue by borgr** [robindijkhof/overleaf-textarea#57]
Could you add a shortcut as pdf is also useful sometimes.

**Comment by Jpfonseca** [comment]
The latest version of the extension is pretty fast to switch between both modes. Just click on the active checkbox.

**Comment by borgr** [comment]
Just say you are understaffed...

**Comment by Jpfonseca** [comment]
> Just say you are understaffed...
 I am not a mantainer. But for the tests I have been doing lately it has been pretty fast compared to what switch used to be in July...

**Comment by borgr** [comment]
I'll rephrase then, a keyboard shortcut. Just getting to the corner with the add on is slow by itself.
