### ISSUE TITLE
Suggestions and one issue

### ISSUE THREAD

**Issue by dsdoermann** [robindijkhof/overleaf-textarea#59]
1) The issue first, When I have \section{Experiment} and want to change it to Experiments, the text area allows me to change but in the overleaf window it shows up as "\section{Experiment}s with the s outside the braces.

2) I don't know if this will be useful for anyone else, but to help navigate, I added some "tag" to the filters.

![image](https://user-images.githubusercontent.com/43833343/130366228-0c07bb24-970a-4dea-b1e1-98b135f46df7.png)

3) Is there any way to edit the filters, rather than deleting and recreating them?

**Comment by robindijkhof** [comment]
I don't think I can fix this first issue. I think this is part of the DiffMatchPatch algorithm.

I'm curious about your second issue. Does this actually do things or is it more like a personal reminder?

For your third point, a created a separate issue.

**Comment by dsdoermann** [comment]
It is more of a way to establish some correspondence between the two windows.  It does not offer any real benefit other then structuring the text in your textarea.


---------------------------
David Doermann
Professor, SUNY Empire Innovation
Professor, Department of Computer Science and Engineering
University at Buffalo

email: ***@***.***
website: cse.buffalo.edu/~doermann<http://cse.buffalo.edu/~doermann>
phone: 716-645-1557 (office), 410-493-9043 (mobile)

[footer_logo_03]
