### ISSUE TITLE
In line citation caused one more space between words that was viewed as error by grammarly

### ISSUE THREAD

**Issue by YunyiShen** [robindijkhof/overleaf-textarea#6]
For example in TeX:
``` tex
PageRank algorithm \cite{brin1998anatomy} was used
```
In the textbox the citation was omitted but left one extra space between "algorithm" and "was"

```diff
PageRank algorithm  was used
```

which was viewed as an error by Grammarly.

**Comment by robindijkhof** [comment]
Thanks I'll check it out. BTW why don't you cite like this? : `PageRank algorithm\cite{brin1998anatomy} was used`

**Comment by robindijkhof** [comment]
Will be fixed in the next release

**Comment by axeis** [comment]
not sure if I should open a new bug as it is related to this one.
sentences like `... shown in \cite{asdf}.` result in an unfinished sentence, which bothers Grammarly.
Is it possible to compile the citation somehow?

**Comment by robindijkhof** [comment]
@axeis I think this should be a new issue. Could you provide me with an sample? A sample with a  few lines, explanation what's wrong and the expected text.
