### ISSUE TITLE
The right bottom corner UI need to be refined. 

### ISSUE THREAD

**Issue by urfdvw** [robindijkhof/overleaf-textarea#61]
![issue](https://user-images.githubusercontent.com/17154432/133665032-84de91fc-a4c6-4ac5-9c2d-011c38c95f79.gif)
A picture is worth a thousand words.
The cursor is just hovering over the icons, not clicking anything.

Win 10 with Chrome 93.

**Comment by robindijkhof** [comment]
This will probably be fixed in the next release.
