### ISSUE TITLE
Render + Text Area

### ISSUE THREAD

**Issue by Benwick921** [robindijkhof/overleaf-textarea#62]
I'd like to swap between the render and text area on Overleaf without enabling and disabling the extension every time.

**Comment by robindijkhof** [comment]
What do you suggest?

**Comment by manuelknott** [comment]
Just a thought: I would find it practical if the text area would replace the rich text tab instead of the rendering part (I think rich text is barely used in general).
Not sure if this is easy to do though.

**Comment by robindijkhof** [comment]
> Just a thought: I would find it practical if the text area would replace the rich text tab instead of the rendering part (I think rich text is barely used in general). Not sure if this is easy to do though.

I have been thinking about that. The problem is that you won't see any it if the plugin makes a mistake.

**Comment by manuelknott** [comment]
I see that point. I am using the plug-in for a while now and I do not check the source code after each change in the text area I accept from Grammarly. I also haven't experienced any mistakes yet. So I personally would rather omit the rich text.

However, I can see the disadvantages it brings. Anyway, thanks for your effort and for sharing the plugin.
