### ISSUE TITLE
Text after \cite ignored until end of line

### ISSUE THREAD

**Issue by TheMrKiko** [robindijkhof/overleaf-textarea#64]
Hello,
I have a paragraph in one LaTeX line with some \cite{} commands in the middle and end; and, in the textarea, everything that is after the first \cite (and until the end of line) does not appear, and is replaced with a dot (.).

I believe this only happens when there is also a command right before the closing dot of the sentence.
The example `Hello this is \cite{ref:a} and this is not \cite{ref:b}.` appears as 

> Hello this is.

and the example `Hello this is \cite{ref:a} and this is not \cite{ref:b}2.` appears as 

> Hello this is and this is not 2.

**Comment by robindijkhof** [comment]
This is solved now
