### ISSUE TITLE
 Nummer of lines is not equal. Cound not apply the fix

### ISSUE THREAD

**Issue by 42Tobi** [robindijkhof/overleaf-textarea#66]
I am not able to use this on any overleaf projects of mine.
After installing the error " Nummer of lines is not equal. Cound not apply the fix" appears in both browsers (Chrome and Firefox).
![grafik](https://user-images.githubusercontent.com/93990406/140932125-738a6c70-8495-4943-9bb9-075be60e188f.png)

**Comment by robindijkhof** [comment]
Seems you are not using the latest version
