### ISSUE TITLE
How to build extension from source to get feature from PR?

### ISSUE THREAD

**Issue by eirik-ff** [robindijkhof/overleaf-textarea#69]
Hi.

Sorry for a noob question, but I could use some guidance. The PR #68 implements a very useful feature and I want to install the plugin with that feature, but I struggle to sign the extension so Firefox will accept it. I've tried to follow a tutorial for signing extensions, but I get an error that I don't own this extension. 

Is there a way to circumvent this error? Or is it possible for the maintainer to accept the PR and publish an updated version of the extension? 

Thanks!

**Comment by robindijkhof** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#trying_it_out

**Comment by robindijkhof** [comment]
See readme
