### ISSUE TITLE
Hidden custom filter form

### ISSUE THREAD

**Issue by mrfarstad** [robindijkhof/overleaf-textarea#7]
When trying to add custom filters, the custom filter form is missing:

![image](https://user-images.githubusercontent.com/22096331/96579038-76c73480-12d6-11eb-99d0-78394a716aee.png)

Tested with incognito mode and all other extensions disabled.

**Comment by robindijkhof** [comment]
This has not yet been released. I'll see what I can do today.

**Comment by robindijkhof** [comment]
It has been released
