### ISSUE TITLE
Wrong replacement for cite

### ISSUE THREAD

**Issue by gege-hoho** [robindijkhof/overleaf-textarea#70]
There seems to be an issue with cite:
`Little et. al. \cite{little} distinguishes between three different mechanisms that lead to missing data \cite{little}.`
Results in 
`Little et. al..`
When I remove the trailing dot, the text is displayed correctly:
`Little et. al. distinguishes between three different mechanisms that lead to missing data `

**Comment by Jpfonseca** [comment]
I haven't looked into it but I believe it's caused by this line
https://github.com/robindijkhof/overleaf-textarea/blob/7e1b59b32cecbba499bf4975b6ca66f103bd0321/source/filter-helper.ts#L22

**Comment by robindijkhof** [comment]
I cannot reproduce it. I might have fixed this before, but not released it. Can you try it again tomorrow after tonight's release?

**Comment by Jpfonseca** [comment]
The behavihour doesn't always happen from my tests

**Comment by Jpfonseca** [comment]
@robindijkhof please merge #73
