### ISSUE TITLE
Wrong "misspelling" position.

### ISSUE THREAD

**Issue by PCLVO** [robindijkhof/overleaf-textarea#71]
Sometimes the location of Grammarly correction is wrong. Refreshing the page does not work. I have realized that there is a CSS style that is the "guilty" of the problem:

*, :after, :before {
    box-sizing: border-box;
}

Disabling this CSS style fixes it. 
To disable it, I have to go to Chrome Dev Tool and do it manually.
Can this be automatically done from the app?

Regards,

P

**Comment by PCLVO** [comment]
You can create a bookmark with the next URL to make that change automatically and also set the text in night mode.
* background-color: is the color of the background
* color: is the color of the font.
Regards.

P
----

javascript:$('<style>').text("textarea#spellcheck-text {font-size: 12.5px;background-color: #272822;color: #e9e9e3;font-family: monospace;").appendTo(document.head);$('<style>').text("*, :after, :before {box-sizing: revert !important;").appendTo(document.head)

**Comment by PCLVO** [comment]
Just in case you want to create a direct-access-bookmark with auto hide-show function:

-----
javascript:
if ($("#spellcheck")[0].style["height"]=="0%" || $("#spellcheck")[0].style["height"]!="98%"){
    $("#spellcheck-text")[0].style["box-sizing"]="unset";
    $("#spellcheck")[0].style["background-color"]="white";
    $("#spellcheck")[0].style["height"]="98%";
    $("#spellcheck")[0].style["font-size"]="12px";
    console.log("done");
} else if ($("#spellcheck")[0].style["height"]=="98%") {
    $("#spellcheck-text")[0].style["box-sizing"]="unset";
    $("#spellcheck")[0].style["background-color"]="white";
    $("#spellcheck")[0].style["height"]="0%";
    $("#spellcheck")[0].style["font-size"]="12px";
    console.log("done");
};

**Comment by PCLVO** [comment]
I've created a function to open the gramarly editor with a a shortcut (CRTL + q).  (This fix only works in CHROME, not in Firefox)
1) Crete a bookmark with this code in the URL field:
--
javascript:
document.onkeyup=function(e){
    var e = e || window.event; 
    if(e.ctrlKey  && e.which == 81) {
        if ($("#spellcheck")[0].style["height"]=="0%" || $("#spellcheck")[0].style["height"]!="98%"){
            $("#spellcheck-text")[0].style["box-sizing"]="unset";
            $("#spellcheck")[0].style["height"]="98%";
        } else if ($("#spellcheck")[0].style["height"]=="98%") {
            $("#spellcheck-text")[0].style["box-sizing"]="unset";
            $("#spellcheck")[0].style["height"]="0%";
        }
        return false;
    }
};
console.log("done")
 --
2) Click on the bookmark
3) Press crtl +q to toggle between the editor and the pdf viewer.

**Comment by robindijkhof** [comment]
I feel a bit hesitant to add this css because I am not sure what side effects it has. Is there a more CSS specific option?

**Comment by PCLVO** [comment]
This command only affects the style of the grammatly texbox, leaving the rest of the webpage as it is:
$("#spellcheck-text")[0].style["box-sizing"]="unset";
That could be implemented within the rest of the code.

**Comment by PCLVO** [comment]
I found a **fix for any browser**. The problem was in the configuration of "grammarly-mirror"
The command to execute in the console is the following:

document.getElementsByTagName("grammarly-mirror")[0].shadowRoot.querySelector("div").style.overflow="auto"

This fixes the problem without changing any other configuration.

**Comment by robindijkhof** [comment]
I'll add this in tonight's release. Can you verify it works?

**Comment by PCLVO** [comment]
> I'll add this in tonight's release. Can you verify it works?

Fixed. It works.
