### ISSUE TITLE
Editor page behind pdf viewer

### ISSUE THREAD

**Issue by PCLVO** [robindijkhof/overleaf-textarea#72]
The editor appears behind the pdf viewer. 
To solve execute the following code in the console:

$("#spellcheck")[0].style["z-index"] = "1";

To open the console: CTRL+SHIFT+J -> Console Tab.
Paste there or create a browser bookmarklet with the javascript code in the URL field.
See: [https://www.freecodecamp.org/news/what-are-bookmarklets/](url)

javascript:
$("#spellcheck")[0].style["z-index"] = "1";

**Comment by abdelix** [comment]
I encountered the same problem and I applied another workaround.
I changed the class of the pdf pane from the developer tools to add the hidden class:
![imagen](https://user-images.githubusercontent.com/1977015/162574150-28d59932-f1d7-49d8-a640-ea1499114145.png)

**Comment by robindijkhof** [comment]
WIll be fixed in tonight's release
