### ISSUE TITLE
Overleaf is testing a new Source Code Editor

### ISSUE THREAD

**Issue by Jpfonseca** [robindijkhof/overleaf-textarea#74]
It seems that Overleaf is currently testing a new Source Code Editor. 
Currently the extension shows some weird behaviour when using this new editor, so I am switching to the old one sometimes. 

In other news, Grammarly can now select the text inside the Source Code Editor altough, sometimes it fails to show the correct suggestions.

**Comment by robindijkhof** [comment]
How can I try this new editor?

**Comment by Jpfonseca** [comment]
I believe it's available through premium now only. Not sure:
https://user-images.githubusercontent.com/11836470/162586237-bfe714cc-b25b-40d9-9182-d087862937d7.mp4

)

**Comment by nic0las2001** [comment]
Hi! I still only have the old editor, however for some reason the text area for grammarly appears behind the compiled pdf and does not let me edit it on chrome. Any idea why this could be?
![oveleaf_textarea_issue](https://user-images.githubusercontent.com/68280106/162586821-50d3afc2-e5aa-48ea-97a2-531ff64f66c2.png)

**Comment by Jpfonseca** [comment]
I have seen similar behaviour. My guess is they are migrating their code.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Jpfonseca** [comment]
Seems like removing the `<div class="pdfViewer">` does the trick. Or at least change its properties

**Comment by nic0las2001** [comment]
Works for me too! Thanks for the tip! I'll use that for now, until Overleaf stops messing around and a fix comes out!

**Comment by robindijkhof** [comment]
I just released to fix that pdf preview. Unfortunately, I don't have premium, so I cannot check it out. Any change you can inspect the element to figure out what editor is used? Previously Ace Editor was used.

**Comment by Jpfonseca** [comment]
@robindijkhof  in the Beta they are using [CodeMirror](https://github.com/codemirror/CodeMirror)  instead of [Ace](https://github.com/ajaxorg/ace)
