### ISSUE TITLE
Commands such as references not showing up in textarea

### ISSUE THREAD

**Issue by mike-gruendler** [robindijkhof/overleaf-textarea#76]
Hi there,

Thank you very much for this awesome plugin!

I have the following issue:

LaTeX:
in section \ref{Linking solutions to challenges} to solution

Textarea:
in section  to solution

The textarea does not show "in section 1.4 to solution" but "in section (double space) to solution".

This is also an issue with \cite and \href for links to websites. This content does not show up, and this messes with the ability of Grammarly to properly check the text since it believes there is a space too much, and sometimes the sentence structure makes no sense without these things.

Thanks for you help!

**Comment by robindijkhof** [comment]
This is by design. Create a new filter to override the behaviour.
