### ISSUE TITLE
Misplaced grammarly Underlines

### ISSUE THREAD

**Issue by Kirmo13** [robindijkhof/overleaf-textarea#79]
When I turn on the Overleaf textarea plugin, all the Grammarly suggestions are at the correct spot. But as soon as I accept one of the suggestions, every underline moves to a different spot.
Has anyone ever faced this issue before? It has always been happening on my device and it's really annoying.

**Comment by PCLVO** [comment]
Downgrade to previous Grammarly Extension version 14.1056.0 on Chrome, Firefox, etc.  That works.

Link to Chrome extension: [https://www.crx4chrome.com/go.php?p=278461&s=5H5D9NWnR2xgI&l=https%3A%2F%2Ff6.crx4chrome.com%2Fcrx.php%3Fi%3Dkbfnbcaeplbcioakkpcpgfkobkghlhen%26v%3D14.1056.0
](Here)

**Comment by Kirmo13** [comment]
It worked first try, thanks for the fix.
