### ISSUE TITLE
Broken link to Firefox Extension

### ISSUE THREAD

**Issue by frafra** [robindijkhof/overleaf-textarea#81]
This link does not work anymore: https://addons.mozilla.org/addon/overleaf-textarea/

**Comment by AntonHartjies** [comment]
It seems the extension is entirely missing from firefox as I have also searched for it manually, and I was unable to find it. This is a great extension that I would love to use on firefox.

**Comment by asantos-6** [comment]
Yes! Anyway we could get it running on Firefox again?

**Comment by aaronkurz** [comment]
Issue still exists...

**Comment by aaronkurz** [comment]
With the updated overleaf editor, the Grammarly extension works natively in FF for me. So that kind of defeats the purpose of the extension, right?

**Comment by robindijkhof** [comment]
@aaronkurz correct. Though I am not sure how it handles LaTeX command. Let me know please.

**Comment by robindijkhof** [comment]
I updated the readme. It now states how to install in FF.

**Comment by robindijkhof** [comment]
This has been fixed now
