### ISSUE TITLE
Errors are always placed in wrong positions by Grammarly when a regex is added

### ISSUE THREAD

**Issue by WunderNatur** [robindijkhof/overleaf-textarea#82]
This is a great plugin! A minor issue: when I was trying to replace math expressions with some placeholder, the errors are always placed in the wrong positions.

I saw in the known issue 

> Sometimes Grammarly is a bit buggy and places the wrong errors in wrong positions. A page refresh usually solves this.

but in my case, they are always in the wrong positions and refreshing does not help.

BTW, I think it would be great if the custom filters can be enabled/disabled individually.

**Comment by robindijkhof** [comment]
I don't think I can do much about this.
