### ISSUE TITLE
The Chrome extension does not work with blank in the textarea

### ISSUE THREAD

**Issue by kelvinzz** [robindijkhof/overleaf-textarea#84]
I disabled all the extensions on Chrome except Grammarly and Overleaf textarea. However, the textarea is blank (see the picture below). Any suggestion would be helpful. Thanks.

![image](https://user-images.githubusercontent.com/23584379/230248379-abae9163-b5a3-45b5-9b8f-8ea4b0c0da1c.png)

**Comment by AllanChain** [comment]
[Overleaf is removing the legacy editor](https://www.overleaf.com/blog/were-retiring-our-legacy-source-editor) and this extension seems incompatible with the new editor. Looking forward to a fix.

**Comment by robindijkhof** [comment]
Is that really necessary? I though the new editor supported grammarly?

**Comment by AllanChain** [comment]
> Is that really necessary? I thought the new editor supported grammarly?

The new editor does support Grammarly, but this extension still offers some features the new editor doesn't provide. For example, the filter feature is really useful to produce a cleaner document for Grammarly and reduce false positives.

It's not so necessary, but I'll prefer to use this extension if it supports the new editor.

**Comment by robindijkhof** [comment]
new version is published

**Comment by robindijkhof** [comment]
@AllanChain, can you confirm it works?

**Comment by AllanChain** [comment]
I gave it a test with Firefox. The textarea shows the document correctly, but when I try to fix the grammar, it also replaces the previous line. Something like:

```diff
-Some content
-You can use emoji-modifiers:
+You can use emoji modifiers:
+You can use emoji modifiers:
```

And the custom filter is having an infinite loop and keeps polluting the content. Something like:

```
/\\emoji\{(.*?)\}/ -> $1
```

```tex
\emoji{rose}\begin{document}
\emoji{rose}\begin{document}
\emoji{rose}\begin{document}
\emoji{rose}\begin{document}
\emoji{rose}\begin{document}
\emoji{rose}\begin{document}
\emoji{rose}\begin{document}
\emoji{rose}\begin{document}
\emoji{rose}\begin{document}
\emoji{rose}
\emoji{rose}
\emoji{rose}
\emoji{rose}
```

Finally, the scroll sync is not working correctly.

---

Seems that the new Overleaf editor is very different from the old one and supporting the new editor takes more effort than I thought... Maybe it's better to just use Grammarly checking in the new editor...

**Comment by robindijkhof** [comment]
@AllanChain that's not something I can reproduce. Everything looks fine. Any chance you can create a reproducible example?

**Comment by AllanChain** [comment]
I tried again today and can't reproduce it either. I don't know what's wrong.
